[words]
"period" = "."
"comma" = ","
"exclamation point" = "!"
"question mark" = "?"
"colon" = ":"
"semicolon" = ";"
"new line" = "\n"
"new paragraph" = "\n\n"
"open paren" = "("
"close paren" = ")"
"open bracket" = "["
"close bracket" = "]"
"open brace" = "{"
"close brace" = "}"
"dash" = "-"
"hyphen" = "-"
"underscore" = "_"
"forward slash" = "/"
"backslash" = "\\"
"ampersand" = "&"
"at sign" = "@"
"hash" = "#"
"dollar sign" = "$"
"percent" = "%"
"equals" = "="
"plus" = "+"
"arrow" = "->"
"fat arrow" = "=>"
"switch commit" = "git add -A && git commit -m \"..\" && git push"
"switch commit." = "git add -A && git commit -m \"..\" && git push"
"switch commit," = "git add -A && git commit -m \"..\" && git push"
"switch, commit" = "git add -A && git commit -m \"..\" && git push"
"switch, commit." = "git add -A && git commit -m \"..\" && git push"
